group: travis_latest
language: node_js
node_js: node
cache: yarn
env:
  global:
  - secure: nLLRO0ZTaKOaT8mQLr1jUjWYvjhIvt8iqIWosTZkBi9cAStqrbqhRwifzVFLJ84YoIuhWWTfysybb+2b9h2YOhD1TbFxvdWdt8j759BE5AwL5Sl0lO0sIN4uWzeVDPQPdVizKiV+UsFfWpETaEnMphO7JILGEGyYSJwcJct2cMpEKrUrQl02kN2qJ4K7+R8NojXJZVmbMW0Sor5Bbf6VLYp6DoWAyMIN2ozOHvnuL0T/LlStRKbI/rUdtEB8LB5HINHiU6D0ZcFj3dSbIA4BN3Y9iWdj4qBhVDHzobc15D1PV3BjOLMZB7rwUyjcWMdo3ssPEwEEkQgZ5+0+t61Y1rkIe+u5rqDZZdkUsK9Bj8u/JYx7YQ3wGHKW1QQIuYEQV2XbQUIMF0Vr2pT+g0cH1q+B4IR/1yPM7f6PwBQeW9zFJTn0DOm5kl6u0SNU4d7l/nXsQu8aekYKxO1/K/Oj4nSKrM+es2x/r3iLLn7gR5HR/rfslcgCNMoIpNxXjDvaUMDz7oagT4yghE8bNmcTULJPvW//ZqtPDeLZdIMlqFVTzB9KCP7PCrkeMceHnbVIIdEhx4YrxndKdiHtDTiitML5L2UqlGn7VpETARPFZj44LtVq81Wb03drDV6hZu++5/W57ydryKX+X5AfFusna5bEo9SkQiDCYMFIoSQwn9c=
  - secure: BhD7AsuTE999DovBYyooWPjMwj9YTpyRH/yxyG9XXcWX0j01ZiwTKwQ2eyOriG6Gj7W/N+4pu+CjKJ5qJINEpYDXhgnXPAVNeVxBcmjXfy2IOCrlbxg1ebPQp5YgVNsCzpRJJw6+1/MLjjkV8wXy8hDf8A4qcZgQnNUf8m3HSbIdpMP84fZZgMxEso0M1qko6M95xjKWtAqLawVqgutKTsGUddTbwrtHcBBnn0jIvYqjVbsbgDh8Y6GRAg7wypanc5GkJgubg3YX6q4FGFVm1P61FWa9juoyrHiyKBL438PERVulsL560NMKVsDQLCeNOrXzzyYHzwBJJHFOIgx59OrV0ThincBt8N2KbLrBLXg7K2iekd1G7vO2xFaEbV1gMCCFmcqqE1TPGvdaHBpXFfTrKBmi3QAH7NSYKu38X+vLkgWt+lixcPeHFGv5IbBTOcxCm/jKcSb+P4UxVnsq4+JqgtBuDOpVM539gc5+Ru/PU8KVMMUtJiYtjE1V4hYJI2u5soXM6yCxvnabXLOMEyhytn2D6mBjRlYn4HR0/a6ExDq3OuEe69xOv+DsjisCRcA3B+1Gap3pm8kylscwQmUQEgv3fZWQRZKdUpx6nwRz5xD8V3nL1PTECOCgsqYutgXC7v9n+n03ah5BbBvKxbKYEhYSugGrbU4NWmdrOE4=
branches:
  only:
    - master
deploy:
  provider: script
  skip_cleanup: true
  script:
  - yarn release
